name: Build Ubports Images

on: 
  push:
    branches:
      - Halium-9
  release:
    types: [published]

jobs:

  focal_build_miami:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Focal Build Miami
      run: |
        set -x
        sudo apt-get update
        sudo apt install build-essential ccache img2simg -y
        sudo wget https://raw.githubusercontent.com/LineageOS/android_system_tools_mkbootimg/lineage-19.1/mkbootimg.py -O /usr/bin/mkbootimg
        sudo chmod 755 /usr/bin/mkbootimg
        ./build.sh - b build
        ./build/prepare-fake-ota.sh out/device_kirin710.tar.xz ota
        ./build/system-image-from-ota.sh ota/ubuntu_command out
        tar -czf out/rootfs.tar.gz out/rootfs.img
        echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      shell: bash
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.NOW }}"
        prerelease: false
        title: "${{ env.NOW }}"
        files: |
          out/rootfs.tar.gz
          out/boot.img
